version: '3.9'
services:
  web:
    restart: on-failure
    build: .
    ports:
      - '81:8090'
    volumes:
      - ./model/:/app/model
      - ./presenter/:/app/presenter
      - ./view/:/app/view
      - ./test:/app/test
  nginx:
    build: ./nginx
    ports:
      - '80:80'
    depends_on:
      - web